**TensorFlow Basics**

**Entire code file were build by taking the help of TensorFlow Official Documentation: `https://www.tensorflow.org/learn`**

- What are Tensors:
- Difference in scalar  , vector , Matrix and Tensor:
- How to create a tensor:
- How to Access tensors:
- How to change tensors values if Already Define:
- Creating Random values:
- Shuffle concept:
- Numpy to TensorFlow:
- TensorFlow to Numpy:
- Finding Extra sections After creating Tensors:
- Basics Math Operations
- Reshape and Transpose 
- Changing Datatype 
- Squeeze 
- Finding Min  , Max , Sum , mean , argmax , argmin ,square , sqrt ,log
- Checking Gpu Availability





In [2]:
import numpy as np 
import tensorflow as tf 


In [2]:
print(tf.__version__)

2.11.0


**First lets check the difference between scalar , vector ,Matrix and tensor**

In mathematical terms, a scalar is a single value, a vector is an ordered array of values, a matrix is a 2D array of values, and a tensor is a multi-dimensional array of values. In PyTorch, scalars are represented as 0-dimensional tensors, vectors are represented as 1-dimensional tensors, matrices are represented as 2-dimensional tensors, and tensors can have more than 2 dimensions.

`so lets creates scalar , vector , matrix and tensors using constant method from tensorflow`

**Default tensorflow will develop values [tensors] with int32 or float32**

In [3]:
scalar = tf.constant(10)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [4]:
scalar = tf.constant(10. , dtype = tf.float64)
scalar

<tf.Tensor: shape=(), dtype=float64, numpy=10.0>

In [5]:
scalar.ndim

0

In [6]:
tf.size(scalar)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [7]:
vector = tf.constant([10 , 2, 3, 11] , dtype = tf.float64)
vector

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([10.,  2.,  3., 11.])>

In [8]:
vector.shape

TensorShape([4])

In [9]:
vector.ndim

1

In [10]:
tf.size(vector)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [11]:
matrix = tf.constant([[1,10,21] , [11,111,41]] , dtype = tf.float64)
matrix 


<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[  1.,  10.,  21.],
       [ 11., 111.,  41.]])>

In [12]:
# we can access values with their position in axis 
# I want to pull out value 41 from above matrix:

matrix[1][2]

<tf.Tensor: shape=(), dtype=float64, numpy=41.0>

In [13]:
matrix.ndim 

2

In [14]:
matrix.shape

TensorShape([2, 3])

In [15]:
tf.size(matrix)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [16]:
tensor = tf.constant([[[1,10,21] , [11,111,41]]] , dtype = tf.float64)
tensor

<tf.Tensor: shape=(1, 2, 3), dtype=float64, numpy=
array([[[  1.,  10.,  21.],
        [ 11., 111.,  41.]]])>

In [17]:
# In the above tensor we are having 2 rows and 3 col and 1 dims 
# for Accessing the value we need to take dims as an consideration:

tensor[0][1][2]  # it is in 0-dim and 1-row and 2-col 

<tf.Tensor: shape=(), dtype=float64, numpy=41.0>

In [18]:
tensor.ndim 

3

In [19]:
tensor.shape 

TensorShape([1, 2, 3])

In [20]:
tf.size(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

**For more details follow tensorflow variable module from here `https://www.tensorflow.org/api_docs/python/tf/Variable`**

In [21]:
## There is also another Method called tensorflow variable which is used to create scalar , vector , matrix and tensors:

# But the tensors created by tensorflow constant which means it is immutable we can't change, 

# Now same as constant but tesors created by variable can easy change there tensors values:

variable_scalar = tf.Variable(10.1 , dtype = tf.float64)

print(variable_scalar)
# print(variable_scalar.ndim)
print(variable_scalar.shape)


<tf.Variable 'Variable:0' shape=() dtype=float64, numpy=10.1>
()


In [22]:

variable_vector = tf.Variable([10.1 , 2.1] , dtype = tf.float64)

print(variable_vector)
# print(variable_scalar.ndim)
print(variable_vector.shape)

<tf.Variable 'Variable:0' shape=(2,) dtype=float64, numpy=array([10.1,  2.1])>
(2,)


In [23]:

variable_matrix = tf.Variable([[10.1 , 2.1,5],[1,2,3]] , dtype = tf.float64)

print(variable_matrix)
# print(variable_scalar.ndim)
print(variable_matrix.shape)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float64, numpy=
array([[10.1,  2.1,  5. ],
       [ 1. ,  2. ,  3. ]])>
(2, 3)


In [24]:
variable_tensor = tf.Variable([[[10.1 , 2.1,5],[1,2,3]]] , dtype = tf.float64)

print(variable_tensor)
# print(variable_scalar.ndim)
print(variable_tensor.shape)

<tf.Variable 'Variable:0' shape=(1, 2, 3) dtype=float64, numpy=
array([[[10.1,  2.1,  5. ],
        [ 1. ,  2. ,  3. ]]])>
(1, 2, 3)


In [25]:
variable_tensor[0][1][2]

<tf.Tensor: shape=(), dtype=float64, numpy=3.0>

In [26]:
## since constant is a immutable lets check 

constant_ = tf.constant([[[1,3,4] , [10,11,12]]] ,dtype = tf.float64)
constant_

<tf.Tensor: shape=(1, 2, 3), dtype=float64, numpy=
array([[[ 1.,  3.,  4.],
        [10., 11., 12.]]])>

In [27]:
# from the above matrix i want to replace value 12 with value 24 --> lets check:

constant_[0][1][2]

<tf.Tensor: shape=(), dtype=float64, numpy=12.0>

In [28]:
constant_[0][1][2] = 24.

TypeError: ignored

In [29]:
# Now variable is mutable let's check it 

variable_ = tf.Variable([10,11,12] , dtype = tf.float64)
variable_

<tf.Variable 'Variable:0' shape=(3,) dtype=float64, numpy=array([10., 11., 12.])>

In [30]:
variable_[2]

<tf.Tensor: shape=(), dtype=float64, numpy=12.0>

In [31]:
variable_[2].assign(24)  # assign method is used to add the value for existing tensor:

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float64, numpy=array([10., 11., 24.])>

In [32]:
variable_

<tf.Variable 'Variable:0' shape=(3,) dtype=float64, numpy=array([10., 11., 24.])>

**Creating Random Tensors:**

`Follow documentation  :https://www.tensorflow.org/api_docs/python/tf/random/normal`

In [33]:
## seed concept is same everywhere like not to generate different different values:
# if we use seed so all the values will be same after many executions also:

In [34]:
# Create two random (but the same) tensors
value1 = tf.random.Generator.from_seed(42)
value1 = value1.uniform(shape = (3,2))
value1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [35]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3, 2)) # create tensor from a normal distribution 
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2
     

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

**Creating a single random tensor**


In [36]:
value = tf.random.uniform(shape = ())
value

<tf.Tensor: shape=(), dtype=float32, numpy=0.9604839>

In [37]:
value = tf.random.normal(shape = ())
value

<tf.Tensor: shape=(), dtype=float32, numpy=-0.21569777>

In [38]:
value = tf.random.normal(shape = (5,6))
value

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[ 1.3345275 ,  0.00539481, -0.8363344 , -0.37406775,  1.3405565 ,
         0.550286  ],
       [-0.34083277, -0.778345  ,  0.02346062,  0.30682805,  1.2187096 ,
        -1.2947935 ],
       [-0.42938223, -0.09969702,  0.17124985, -0.5511038 ,  0.7477511 ,
        -0.2633123 ],
       [ 1.0339829 ,  1.1837286 , -0.42881265, -0.9093057 ,  0.5934744 ,
         1.1250869 ],
       [ 1.3403276 ,  1.2939974 ,  0.9693469 , -0.74248904,  0.22531442,
        -0.451263  ]], dtype=float32)>

**shuffle** 

Tensorflow Random shuffle `https://www.tensorflow.org/api_docs/python/tf/random/shuffle`

In [39]:
# just to shuffle the data Randomlly:

value = tf.constant([[1,2,1] , [10,11,100],[21,221,200]],dtype = tf.float64)
print(value)
shuffle_values = tf.random.shuffle(value = value)
print(shuffle_values)

tf.Tensor(
[[  1.   2.   1.]
 [ 10.  11. 100.]
 [ 21. 221. 200.]], shape=(3, 3), dtype=float64)
tf.Tensor(
[[  1.   2.   1.]
 [ 21. 221. 200.]
 [ 10.  11. 100.]], shape=(3, 3), dtype=float64)


In [40]:
# For Making shuffle data Not to change Just used seed:
value1 = tf.constant([[1,2,1] , [10,11,100],[21,221,200]],dtype = tf.float64)
print(value1)

tf.Tensor(
[[  1.   2.   1.]
 [ 10.  11. 100.]
 [ 21. 221. 200.]], shape=(3, 3), dtype=float64)


In [41]:
tf.random.set_seed(42)
shuffle_values = tf.random.shuffle(value = value1)
print(shuffle_values)

tf.Tensor(
[[ 10.  11. 100.]
 [ 21. 221. 200.]
 [  1.   2.   1.]], shape=(3, 3), dtype=float64)


**Zeros**

`Making tensors with complete Zero https://www.tensorflow.org/api_docs/python/tf/zeros`



In [42]:
tensor_zero = tf.zeros(shape = (3,3) , dtype = tf.float32)
tensor_zero

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [43]:
tensor_zero = tf.zeros(shape = (5,3) , dtype = tf.int32)
tensor_zero

<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)>

**Ones**

`Creating Tensors with complete ones: https://www.tensorflow.org/api_docs/python/tf/ones`

In [44]:
tensor_ones = tf.ones(shape = (5,6), dtype = tf.float32)
tensor_ones

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [45]:
tensor_ones = tf.ones(shape = (5,6), dtype = tf.float64)
tensor_ones

<tf.Tensor: shape=(5, 6), dtype=float64, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])>

**Numpy to Tensorflow**

`Convert Numpy to TensorFlow https://www.tensorflow.org/api_docs/python/tf/convert_to_tensor`



In [46]:
# This is not array values generated By tensorflow:

import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
A = tf.constant(numpy_A,  
                shape=[2, 4, 3]) # note: the shape total (2*4*3) has to match the number of elements in the array
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

In [47]:
A[1][1][1]

<tf.Tensor: shape=(), dtype=int32, numpy=17>

In [48]:
numpy_to_tensor = np.array([[1,2,3] , [10,11,12]],dtype= np.float64)
print(numpy_to_tensor)
print(type(numpy_to_tensor))

[[ 1.  2.  3.]
 [10. 11. 12.]]
<class 'numpy.ndarray'>


In [49]:
numpy_to_tensor = tf.convert_to_tensor(numpy_to_tensor)
print(numpy_to_tensor)
print(type(numpy_to_tensor))

tf.Tensor(
[[ 1.  2.  3.]
 [10. 11. 12.]], shape=(2, 3), dtype=float64)
<class 'tensorflow.python.framework.ops.EagerTensor'>


**TensorFlow to Numpy**




In [50]:
tensor_to_numpy = tf.constant([[1,2,3], [10,11,12]],dtype = tf.float64)
tensor_to_numpy

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[ 1.,  2.,  3.],
       [10., 11., 12.]])>

In [51]:
t_n = tf.make_tensor_proto(tensor_to_numpy)
t_n = tf.make_ndarray(t_n)
print(t_n)

[[ 1.  2.  3.]
 [10. 11. 12.]]


In [52]:
print(type(t_n))

<class 'numpy.ndarray'>


**second way**

In [107]:
tensor_to_numpy = tf.constant([[1,2,3], [10,11,12]],dtype = tf.float64)
tensor_to_numpy = np.array(tensor_to_numpy)
tensor_to_numpy

array([[ 1.,  2.,  3.],
       [10., 11., 12.]])

In [108]:
type(tensor_to_numpy)

numpy.ndarray

**third_way**

In [109]:
tensor_to_numpy = tf.constant([[1,2,3], [10,11,12]],dtype = tf.float64)
tensor_to_numpy = tensor_to_numpy.numpy()
tensor_to_numpy

array([[ 1.,  2.,  3.],
       [10., 11., 12.]])

In [110]:
type(tensor_to_numpy)

numpy.ndarray

**convert GPU Created Tensors into Numpy**



In [12]:
import tensorflow as tf
import tensorflow.compat.v1 as tf
import numpy as np

# create a tensor on GPU
with tf.device('/gpu:0'):
    tensor = tf.ones((3, 3))
print(type(tensor))
# convert tensor to numpy
with tf.Session() as sess:
    np_array = tensor.numpy()

print(np_array)
print(type(np_array))

<class 'tensorflow.python.framework.ops.EagerTensor'>
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.ndarray'>


**Information About Tensors After creation**

`Shape:` The length (number of elements) of each of the dimensions of a tensor.

`Rank:` The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.

`Axis or Dimension:` A particular dimension of a tensor.

`Size:` The total number of items in the tensor.

In [53]:
rank_4_tensor = tf.ones([3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [54]:
rank_4_tensor.shape , rank_4_tensor.ndim , tf.size(rank_4_tensor).numpy()

(TensorShape([3, 4, 5]), 3, 60)

**TensorFlow Expand Dimensions**

`using Expand_dims we can create inner dims , outer dims very easily https://www.tensorflow.org/api_docs/python/tf/expand_dims`

In [55]:
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])


In [56]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [57]:
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [58]:
tf.expand_dims(rank_2_tensor, axis=1) # "1" means middle axis

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [59]:
tf.expand_dims(rank_2_tensor, axis=0) # "0" means beginging axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [60]:
# For 3d data:

rank_2_tensor = tf.constant([[[10, 7,1],[3, 4,10] , [11,21,22]]])
rank_2_tensor

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[10,  7,  1],
        [ 3,  4, 10],
        [11, 21, 22]]], dtype=int32)>

In [61]:
tf.expand_dims(rank_2_tensor, axis=0) # "0" means beginging axis

<tf.Tensor: shape=(1, 1, 3, 3), dtype=int32, numpy=
array([[[[10,  7,  1],
         [ 3,  4, 10],
         [11, 21, 22]]]], dtype=int32)>

In [62]:
tf.expand_dims(rank_2_tensor, axis=1) # "1" means Middle axis

<tf.Tensor: shape=(1, 1, 3, 3), dtype=int32, numpy=
array([[[[10,  7,  1],
         [ 3,  4, 10],
         [11, 21, 22]]]], dtype=int32)>

In [63]:
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means end axis

<tf.Tensor: shape=(1, 3, 3, 1), dtype=int32, numpy=
array([[[[10],
         [ 7],
         [ 1]],

        [[ 3],
         [ 4],
         [10]],

        [[11],
         [21],
         [22]]]], dtype=int32)>

**Basic Math Operations**

`official Documentation : https://www.tensorflow.org/api_docs/python/tf/math/`

- Addition 
- Subtraction 
- Multiplication 
- Division 
- MatMul

In [64]:
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [65]:
tensor = tf.constant([[10, 7], [3, 4]])
tf.add(tensor , 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [66]:
tensor = tf.constant([[10, 7], [3, 4]])
tf.subtract(10 , tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 3],
       [7, 6]], dtype=int32)>

In [67]:
tensor = tf.constant([[10, 7], [3, 4]])
tf.multiply(tensor , 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [68]:
tensor = tf.constant([[10, 7], [3, 4]])
tf.divide(tensor , 10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [69]:
# matmul 

tensor_1 = tf.constant([[5,0,3], [3,7,9] , [3,5,2]] , dtype = tf.float64)
print(tensor_1)  # 3 * 3 matrix 
print(tensor_1.shape)
tensor_2 = tf.constant([[4,7], [6,8] , [8,1]] , dtype = tf.float64)
print(tensor_2)
print(tensor_2.shape)

# apply matmul 

result = tf.matmul(tensor_1 , tensor_2)

tf.Tensor(
[[5. 0. 3.]
 [3. 7. 9.]
 [3. 5. 2.]], shape=(3, 3), dtype=float64)
(3, 3)
tf.Tensor(
[[4. 7.]
 [6. 8.]
 [8. 1.]], shape=(3, 2), dtype=float64)
(3, 2)


In [70]:
print(result)

tf.Tensor(
[[ 44.  38.]
 [126.  86.]
 [ 58.  63.]], shape=(3, 2), dtype=float64)


**reshape and transpose**

- `reshape : https://www.tensorflow.org/api_docs/python/tf/reshape`

- `Transpose : https://www.tensorflow.org/api_docs/python/tf/transpose`

In [71]:
reshape_tensor = tf.constant([[5,0,3 , 1], [3,7,9,9] , [3,5,2,8]] , dtype = tf.float64)
reshape_tensor

<tf.Tensor: shape=(3, 4), dtype=float64, numpy=
array([[5., 0., 3., 1.],
       [3., 7., 9., 9.],
       [3., 5., 2., 8.]])>

In [72]:
tf.reshape(reshape_tensor, [6,2])


<tf.Tensor: shape=(6, 2), dtype=float64, numpy=
array([[5., 0.],
       [3., 1.],
       [3., 7.],
       [9., 9.],
       [3., 5.],
       [2., 8.]])>

In [73]:
tf.reshape(reshape_tensor, [3,2,2])


<tf.Tensor: shape=(3, 2, 2), dtype=float64, numpy=
array([[[5., 0.],
        [3., 1.]],

       [[3., 7.],
        [9., 9.]],

       [[3., 5.],
        [2., 8.]]])>

In [74]:
transpose_tensor = tf.constant([[5,0,3 , 1], [3,7,9,9] , [3,5,2,8]] , dtype = tf.float64)
transpose_tensor

<tf.Tensor: shape=(3, 4), dtype=float64, numpy=
array([[5., 0., 3., 1.],
       [3., 7., 9., 9.],
       [3., 5., 2., 8.]])>

In [75]:
# transpose 

# Create a 2D tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6] , [10,11,12]])

# Perform transpose operation
transposed_tensor = tf.transpose(tensor)

# Display the result
print("Original tensor:\n", tensor.numpy())
print("Transposed tensor:\n", transposed_tensor)


Original tensor:
 [[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]
Transposed tensor:
 tf.Tensor(
[[ 1  4 10]
 [ 2  5 11]
 [ 3  6 12]], shape=(3, 3), dtype=int32)


**Changing Datatypes**

- `using cast we can change data type : https://www.tensorflow.org/api_docs/python/tf/cast`

In [76]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6] , [10,11,12]] , dtype = tf.float64)
tensor


<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [10., 11., 12.]])>

In [77]:
tf.cast(tensor , tf.float32)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [10., 11., 12.]], dtype=float32)>

In [78]:
tf.cast(tensor, tf.int32)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]], dtype=int32)>

**Getting Absolute Value**



In [79]:
value = tf.constant([-100 , 100])

tf.abs(value)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([100, 100], dtype=int32)>

**Finding Min , Max , Mean ,Sum in a tensor**

- `tf.reduce_min()` - find the minimum value in a tensor.
- `tf.reduce_max()` - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).
- `tf.reduce_mean()` - find the mean of all elements in a tensor.
- `tf.reduce_sum()` - find the sum of all elements in a tensor.

`Note`: typically, each of these is under the math module, e.g. tf.math.reduce_min() but you can use the alias tf.reduce_min().

In [80]:
values = tf.constant([[1,2,3] , [10,11,12]])
values 

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [10, 11, 12]], dtype=int32)>

In [81]:
tf.reduce_min(values , axis = 1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 1, 10], dtype=int32)>

In [82]:
tf.reduce_min(values , axis = 0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [83]:
tf.reduce_max(values , axis = 1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 3, 12], dtype=int32)>

In [84]:
tf.reduce_mean(values , axis = 1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 2, 11], dtype=int32)>

In [85]:
tf.reduce_sum(values , axis = 1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 6, 33], dtype=int32)>

In [86]:
tf.argmax(values , axis = 1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 2])>

In [87]:
tf.argmin(values , axis = 1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 0])>

**Squeeze and Unsqueeze**

- `Squeeze:` `Removes all the one dims from the given tensor`
- `Unsqueze:` `As worked in PyTorch Unsqueeze is not available in tensorflow but use tf.expand_dims because it is same as unsqueeze in PyTorch` `Adds all the one dims from the given tensor`

In [93]:
values = tf.constant([1,2,3])
values = tf.reshape(values , [1,3])
print(values)
dims_remove = tf.squeeze(values)
print(dims_remove)


tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


- `tf.square()` - get the square of every value in a tensor.
- `tf.sqrt()` - get the squareroot of every value in a tensor (note: the elements need to be floats or this will error).
- `tf.math.log()` - get the natural log of every value in a tensor (elements need to floats).

In [96]:
values = tf.constant([[1,2,3] , [10,11,12]] , dtype = tf.float64)

values 

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[ 1.,  2.,  3.],
       [10., 11., 12.]])>

In [97]:
tf.square(values)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[  1.,   4.,   9.],
       [100., 121., 144.]])>

In [98]:
tf.sqrt(values)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1.        , 1.41421356, 1.73205081],
       [3.16227766, 3.31662479, 3.46410162]])>

In [99]:
tf.math.log(values)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0.        , 0.69314718, 1.09861229],
       [2.30258509, 2.39789527, 2.48490665]])>

**Finding Accesss to GPU**


In [3]:
print(tf.config.list_physical_devices('GPU'))
     

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [4]:

!nvidia-smi

Wed Feb 15 05:23:12 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P0    26W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------